In this notebook, we will cover some of the basic topics related to pandas  and learn some basic dataframe operations like **Sorting**,**Subsetting** and **Creating new columns**.

### Introduction to Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,built on top of the Python programming language.Pandas is built on top Numpy and Matplotlib.

In [1]:
import pandas as pd

Lets import [bank churn data](https://www.kaggle.com/datasets/mathchi/churn-for-bank-customers?resource=download) set from kaggle.

In [5]:
df = pd.read_csv('data/churn.csv')

`df.head`: Gives the top 10 values of the dataset

In [6]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

`df.describe()`: This function will provide a brief descriptive statistics about the dataset.

In [7]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

`df.shape`: This function provides the shape of the dataset.

In [9]:
df.shape

(10000, 14)

`df.values`: This attribute provides all the data values in a 2d numpy array.

In [10]:
print(df.values)

[[1 15634602 'Hargrave' ... 1 101348.88 1]
 [2 15647311 'Hill' ... 1 112542.58 0]
 [3 15619304 'Onio' ... 0 113931.57 1]
 ...
 [9998 15584532 'Liu' ... 1 42085.58 1]
 [9999 15682355 'Sabbatini' ... 0 92888.52 1]
 [10000 15628319 'Walker' ... 0 38190.78 0]]

`df.columns`: This attributes provides column values of the dataframe.

In [11]:
print(df.columns)

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

`df.index`: This attribute contains the row index of the dataframe.

In [12]:
df.index

RangeIndex(start=0, stop=10000, step=1)

### Sorting and subsetting:

`df.sort_values(<'column_name'>, ascending=True/False)`: This will sort the dataset based on a particular column

In [13]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [14]:
df.sort_values('Geography')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
5577,5578,15726087,Ch'in,592,France,Female,62,5,0.00,1,1,1,100941.57,0
5575,5576,15782879,Lang,656,France,Male,40,2,0.00,2,1,1,180553.48,0
5573,5574,15628893,Power,681,France,Male,29,8,0.00,1,1,0,66367.33,0
5572,5573,15613140,Mellor,565,France,Male,34,6,0.00,1,1,1,63173.64,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6611,6612,15715199,Estrada,568,Spain,Male,27,5,126815.97,2,0,1,118648.12,0
1712,1713,15744983,Burgmann,712,Spain,Male,47,1,139887.01,1,1,1,95719.73,0
1710,1711,15567993,Palmer,828,Spain,Male,28,8,134766.85,1,1,0,79355.87,0
6537,6538,15782364,Bevan,521,Spain,Female,39,3,146408.68,1,0,0,72993.67,0
4999,5000,15710408,Cunningham,584,Spain,Female,38,3,0.00,2,1,1,4525.40,0

In [15]:
df.sort_values('Geography', ascending=False)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
6666,6667,15798709,Gill,588,Spain,Male,32,3,109109.33,1,0,1,4993.94,0
8953,8954,15592925,Giordano,711,Spain,Male,42,3,177626.77,3,0,1,16392.72,1
2145,2146,15639322,Grave,633,Spain,Male,33,4,137847.41,2,1,0,98349.13,0
4852,4853,15574137,Ch'in,687,Spain,Male,35,3,0.00,2,1,1,176450.19,0
2148,2149,15811842,Artemyeva,630,Spain,Male,26,7,0.00,2,1,1,6656.64,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4439,4440,15696539,Wade,613,France,Female,21,7,105627.95,1,1,1,36560.51,0
4437,4438,15779522,Efimov,736,France,Female,24,0,0.00,2,1,0,109355.73,1
4436,4437,15664498,Golovanov,508,France,Male,26,7,205962.00,1,1,0,156424.40,0
4433,4434,15724099,Udinese,674,France,Male,26,6,166257.96,1,1,1,149369.41,0
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [16]:
# Sorting by multiple variables
df.sort_values(['Geography','Surname'])

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
841,842,15737792,Abbie,818,France,Female,31,1,186796.37,1,0,0,178252.63,0
2537,2538,15723706,Abbott,573,France,Female,33,0,90124.64,1,1,0,137476.71,0
2988,2989,15684801,Abbott,689,France,Male,47,1,93871.95,3,1,0,156878.42,1
4573,4574,15693906,Abbott,645,France,Female,24,3,34547.82,1,1,1,11638.17,0
6838,6839,15680804,Abbott,850,France,Male,29,6,0.00,2,1,1,10672.54,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2656,2657,15713267,Zimmer,779,Spain,Female,34,5,0.00,2,0,1,111676.63,0
4790,4791,15642022,Zito,621,Spain,Male,34,8,0.00,1,0,0,47972.65,0
6641,6642,15591942,Zito,611,Spain,Female,33,7,0.00,2,1,1,3729.89,0
586,587,15722010,Zuyev,621,Spain,Male,53,9,170491.84,1,1,0,35588.07,1
7739,7740,15689952,Zuyeva,724,Spain,Male,41,5,0.00,1,0,1,115753.94,0

In [17]:
df.sort_values(['Geography','Surname'], ascending=[True, False])

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1030,1031,15681174,Zuev,730,France,Male,39,1,116537.60,1,0,0,145679.60,0
2946,2947,15727696,Zubareva,592,France,Male,42,1,147249.29,2,1,1,63023.02,0
5676,5677,15568104,Zubarev,749,France,Female,26,6,0.00,2,0,1,34948.77,0
6939,6940,15807433,Zubarev,570,France,Female,43,9,0.00,2,0,1,11417.26,0
8814,8815,15589725,Zubarev,740,France,Female,51,4,0.00,2,1,1,178929.84,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7658,7659,15666297,Abramova,706,Spain,Female,53,3,0.00,3,0,0,88479.02,1
9373,9374,15807457,Abernathy,641,Spain,Female,36,1,0.00,2,1,0,102021.39,0
6327,6328,15793856,Abdulov,667,Spain,Female,36,3,121542.57,2,1,1,186841.71,0
3271,3272,15708791,Abazu,584,Spain,Male,32,9,85534.83,1,0,0,169137.24,0
5109,5110,15576156,Abazu,710,Spain,Female,28,6,0.00,1,1,0,48426.98,0

`df['<Column_Name'>]`: This is called subsetting a column from the dataframe.

In [18]:
df['Surname']

0        Hargrave
1            Hill
2            Onio
3            Boni
4        Mitchell
          ...
9995     Obijiaku
9996    Johnstone
9997          Liu
9998    Sabbatini
9999       Walker
Name: Surname, Length: 10000, dtype: object

`df[['<Column_Name1>',''<Column_Name2>'']]`: This is called subsetting multiple columns from the dataframe.

In [20]:
df[['Geography','Surname']]

     Geography    Surname
0       France   Hargrave
1        Spain       Hill
2       France       Onio
3       France       Boni
4        Spain   Mitchell
...        ...        ...
9995    France   Obijiaku
9996    France  Johnstone
9997    France        Liu
9998   Germany  Sabbatini
9999    France     Walker

[10000 rows x 2 columns]

In [21]:
# One more method
col_name = ['Geography','Surname']
df[col_name]

     Geography    Surname
0       France   Hargrave
1        Spain       Hill
2       France       Onio
3       France       Boni
4        Spain   Mitchell
...        ...        ...
9995    France   Obijiaku
9996    France  Johnstone
9997    France        Liu
9998   Germany  Sabbatini
9999    France     Walker

[10000 rows x 2 columns]

In [22]:
# Filtering data using subsetting
df['CreditScore'] > 700

0       False
1       False
2       False
3       False
4        True
        ...
9995     True
9996    False
9997     True
9998     True
9999     True
Name: CreditScore, Length: 10000, dtype: bool

In [23]:
#Filtering across the dataframe
df[df['CreditScore'] > 700]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0
20,21,15577657,McDonald,732,France,Male,41,8,0.00,2,1,1,170886.17,0
24,25,15625047,Yen,846,France,Female,38,5,0.00,1,1,1,187616.16,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [24]:
# Subestting based on Text
df[df['Geography'] == 'Spain']

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9966,9967,15590213,Ch'en,479,Spain,Male,35,4,125920.98,1,1,1,20393.44,0
9980,9981,15719276,T'ao,741,Spain,Male,35,6,74371.49,1,0,0,99595.67,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0

In [27]:
# Subsetting based on multiple conditions
isCredit = df['CreditScore'] > 700
isSpain = df['Geography'] == 'Spain'
df[isCredit &  isSpain]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
34,35,15732963,Clements,722,Spain,Female,29,9,0.00,2,1,1,142033.07,0
37,38,15729599,Lorenzo,804,Spain,Male,33,7,76548.60,1,0,1,98453.45,0
78,79,15575185,Bushell,757,Spain,Male,33,5,77253.22,1,0,1,194239.63,0
86,87,15762418,Gant,750,Spain,Male,22,3,121681.82,1,1,0,128643.35,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9959,9960,15677783,Graham,764,Spain,Male,38,4,113607.47,1,1,0,91094.46,0
9962,9963,15594612,Flynn,702,Spain,Male,44,9,0.00,1,0,0,59207.41,1
9980,9981,15719276,T'ao,741,Spain,Male,35,6,74371.49,1,0,0,99595.67,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0

In [29]:
df[(df['Geography'] == 'Spain') & (df['CreditScore'] > 700)]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
34,35,15732963,Clements,722,Spain,Female,29,9,0.00,2,1,1,142033.07,0
37,38,15729599,Lorenzo,804,Spain,Male,33,7,76548.60,1,0,1,98453.45,0
78,79,15575185,Bushell,757,Spain,Male,33,5,77253.22,1,0,1,194239.63,0
86,87,15762418,Gant,750,Spain,Male,22,3,121681.82,1,1,0,128643.35,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9959,9960,15677783,Graham,764,Spain,Male,38,4,113607.47,1,1,0,91094.46,0
9962,9963,15594612,Flynn,702,Spain,Male,44,9,0.00,1,0,0,59207.41,1
9980,9981,15719276,T'ao,741,Spain,Male,35,6,74371.49,1,0,0,99595.67,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0

`isin()`: This method is used to check some logical condition from the dataframe.

In [30]:
df['Geography'].isin(['France','Spain'])

0        True
1        True
2        True
3        True
4        True
        ...
9995     True
9996     True
9997     True
9998    False
9999     True
Name: Geography, Length: 10000, dtype: bool