In this notebook , we will cover some topics related to aggregation of data.This includes topics like **Summary Statistics**, **Counting** , **Grouped Statistics**.

In [1]:

import pandas as pd
import numpy as np

For this section , we will use the wallmart dataset . This dataset contains all the weekly sales, temperature and all the other details realted to sales that occurs a any walmart store. For more information about the dataset follow this [Link.](https://www.kaggle.com/datasets/yasserh/walmart-dataset)

In [4]:
df = pd.read_csv('data/Walmart.csv')
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [5]:
df.columns

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='object')

### Summary Statistics:

Summary Statistics is as the name suggests are numbers that summarize or tell ur about the dataset.

`df.mean()`: Will porvide the center of our dataset.

In [20]:
print(df['Fuel_Price'].mean())

3.358606837606838

`df.median()`: Also provides the middle value of the dataset.

In [19]:
print(df['CPI'].median())

182.6165205

`df.mode()`: Provides the most frequent values of the dataset.

In [18]:
print(df['Unemployment'].mode())

0    8.099
Name: Unemployment, dtype: float64

`df.min()`: Provides the minimum value of the column

In [17]:
print(df['Weekly_Sales'].min())

209986.25

`df.max()`: Provides the maxiumum value of the column

In [16]:
print(df['Weekly_Sales'].max())

3818686.45

`df.var()`: Provides the spread of the datapoint around their mean.

In [15]:
print(df['Fuel_Price'].var())

0.21069909159141206

`df.std()`: Provides the dispersion of data points relative to their mean.

In [14]:
print(df['Fuel_Price'].std())

0.4590197071928525

`df.sum()`: summation of the values of that column

In [21]:
print(df['Fuel_Price'].sum())

21612.635000000002

`df.agg()`: Aggregation of value of a dataset.

In [23]:
print(df['Fuel_Price'].agg('max'))

4.468

`df.cumsum()`: return the cumulative sum over a DataFrame or Series axis

In [24]:
print(df.cumsum())

       Store                                               Date  Weekly_Sales  \
0          1                                         05-02-2010  1.643691e+06
1          2                               05-02-201012-02-2010  3.285648e+06
2          3                     05-02-201012-02-201019-02-2010  4.897617e+06
3          4           05-02-201012-02-201019-02-201026-02-2010  6.307344e+06
4          5  05-02-201012-02-201019-02-201026-02-201005-03-...  7.862151e+06
...      ...                                                ...           ...
6430  147825  05-02-201012-02-201019-02-201026-02-201005-03-...  6.734273e+09
6431  147870  05-02-201012-02-201019-02-201026-02-201005-03-...  6.735006e+09
6432  147915  05-02-201012-02-201019-02-201026-02-201005-03-...  6.735741e+09
6433  147960  05-02-201012-02-201019-02-201026-02-201005-03-...  6.736459e+09
6434  148005  05-02-201012-02-201019-02-201026-02-201005-03-...  6.737219e+09

      Holiday_Flag  Temperature  Fuel_Price           CPI  Unemployment
0                0        42.31       2.572  2.110964e+02         8.106
1                1        80.82       5.120  4.223385e+02        16.212
2                1       120.75       7.634  6.336277e+02        24.318
3                1       167.38      10.195  8.449473e+02        32.424
4                1       213.88      12.820  1.056297e+03        40.530
...            ...          ...         ...           ...           ...
6430           450    390136.76   21596.799  1.103338e+06     51439.869
6431           450    390201.65   21600.784  1.103530e+06     51448.536
6432           450    390256.12   21604.784  1.103722e+06     51457.203
6433           450    390312.59   21608.753  1.103915e+06     51465.870
6434           450    390371.44   21612.635  1.104107e+06     51474.537

[6435 rows x 8 columns]

## Cumulative Statistics

`df.cummax()`: functions are used to calculate the cumulative maximum of values along a specified axis

In [25]:
print(df.cummax())

      Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0         1  05-02-2010    1643690.90             0        42.31       2.572
1         1  12-02-2010    1643690.90             1        42.31       2.572
2         1  19-02-2010    1643690.90             1        42.31       2.572
3         1  26-02-2010    1643690.90             1        46.63       2.572
4         1  26-02-2010    1643690.90             1        46.63       2.625
...     ...         ...           ...           ...          ...         ...
6430     45  31-12-2010    3818686.45             1       100.14       4.468
6431     45  31-12-2010    3818686.45             1       100.14       4.468
6432     45  31-12-2010    3818686.45             1       100.14       4.468
6433     45  31-12-2010    3818686.45             1       100.14       4.468
6434     45  31-12-2010    3818686.45             1       100.14       4.468

             CPI  Unemployment
0     211.096358         8.106
1     211.242170         8.106
2     211.289143         8.106
3     211.319643         8.106
4     211.350143         8.106
...          ...           ...
6430  227.232807        14.313
6431  227.232807        14.313
6432  227.232807        14.313
6433  227.232807        14.313
6434  227.232807        14.313

[6435 rows x 8 columns]

`df.cumin()`:functions are used to calculate the cumulative minimum of values along a specified axis

In [26]:
print(df.cummin())

      Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \
0         1  05-02-2010    1643690.90             0        42.31       2.572
1         1  05-02-2010    1641957.44             0        38.51       2.548
2         1  05-02-2010    1611968.17             0        38.51       2.514
3         1  05-02-2010    1409727.59             0        38.51       2.514
4         1  05-02-2010    1409727.59             0        38.51       2.514
...     ...         ...           ...           ...          ...         ...
6430      1  01-04-2011     209986.25             0        -2.06       2.472
6431      1  01-04-2011     209986.25             0        -2.06       2.472
6432      1  01-04-2011     209986.25             0        -2.06       2.472
6433      1  01-04-2011     209986.25             0        -2.06       2.472
6434      1  01-04-2011     209986.25             0        -2.06       2.472

             CPI  Unemployment
0     211.096358         8.106
1     211.096358         8.106
2     211.096358         8.106
3     211.096358         8.106
4     211.096358         8.106
...          ...           ...
6430  126.064000         3.879
6431  126.064000         3.879
6432  126.064000         3.879
6433  126.064000         3.879
6434  126.064000         3.879

[6435 rows x 8 columns]

`df.cumprod()`:The cumprod() function in pandas is used to calculate the cumulative product of values along a specified axis (index or columns) of a Series or DataFrame

In [ ]:
print(df.cumprod(skipna=False))

## Counting

We will use summary statistcs to count the value in a dataset.

`df.drop_duplicates[subset="<Column_name>"]`: This function will drop all duplicate values in the provided dataset and keep only the unique ones.


``` Note```: For passing multiple columns inside any function in pandas, Pandas always requires a list hence the given columns must be inside square brackets

In [30]:
df.columns

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='object')

In [31]:
df.drop_duplicates(subset=['Weekly_Sales','Temperature'])

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

`df.value_counts()`: Counts the number of occurance of that particular value inside the dataset.

In [32]:
df.value_counts()

Store  Date        Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  CPI         Unemployment
1      01-04-2011  1495064.75    0             59.17        3.524       214.837166  7.682           1
30     30-09-2011  387001.13     0             78.91        3.355       216.362033  7.852           1
31     02-07-2010  1311704.92    0             82.29        2.669       210.880373  8.099           1
       02-04-2010  1357600.68    0             64.12        2.719       210.479887  8.200           1
       02-03-2012  1427881.22    0             59.30        3.630       220.486689  7.057           1
                                                                                                   ..
15     30-12-2011  603460.79     1             31.44        3.566       136.643258  7.866           1
       30-09-2011  521297.31     0             64.87        3.858       136.419500  7.806           1
       30-07-2010  619224.06     0             72.04        2.932       132.598387  8.099           1
       30-04-2010  570791.11     0             49.09        3.042       132.064433  8.185           1
45     31-12-2010  679156.20     1             29.67        3.179       182.571448  8.724           1
Name: count, Length: 6435, dtype: int64

In [33]:
df.value_counts(sort=True)

Store  Date        Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  CPI         Unemployment
1      01-04-2011  1495064.75    0             59.17        3.524       214.837166  7.682           1
30     30-09-2011  387001.13     0             78.91        3.355       216.362033  7.852           1
31     02-07-2010  1311704.92    0             82.29        2.669       210.880373  8.099           1
       02-04-2010  1357600.68    0             64.12        2.719       210.479887  8.200           1
       02-03-2012  1427881.22    0             59.30        3.630       220.486689  7.057           1
                                                                                                   ..
15     30-12-2011  603460.79     1             31.44        3.566       136.643258  7.866           1
       30-09-2011  521297.31     0             64.87        3.858       136.419500  7.806           1
       30-07-2010  619224.06     0             72.04        2.932       132.598387  8.099           1
       30-04-2010  570791.11     0             49.09        3.042       132.064433  8.185           1
45     31-12-2010  679156.20     1             29.67        3.179       182.571448  8.724           1
Name: count, Length: 6435, dtype: int64

`df.value_counts(normail=True)`: Will provide overall distribution of the column counts inside the dataset.

In [34]:
df['Fuel_Price'].value_counts()

Fuel_Price
3.638    39
3.630    34
2.771    29
3.891    29
3.524    28
         ..
2.863     1
2.995     1
3.053     1
3.448     1
3.576     1
Name: count, Length: 892, dtype: int64

### Grouped Summary Statistics:

We can group two or more columns and hence summarize those using grouped summary statistics.

`df.groupby("Column_1")["Column_2"].mean()`

In [36]:
df.groupby("CPI")['Temperature'].mean()

CPI
126.064000    82.106364
126.076645    84.513636
126.085452    84.269091
126.089290    82.410000
126.101935    76.950000
                ...
227.018417    62.990000
227.036936    64.740000
227.169392    60.090000
227.214288    68.010000
227.232807    69.520000
Name: Temperature, Length: 2145, dtype: float64

`df.groupby("Column_1")["Column_2"].agg[min,max,sum]`

In [ ]:
df.groupby("CPI")["Weekly_Sales"].agg[max]

## Pivot Tables:

`df.pivot_table(values='column_name1',index='color')`: here we can get a grouped summary staistics using pivot tables . By default, the pivot table functions takes in the mean. We can change that using `aggfunc` method and change the desired statistics.

1. `Columns argument`: creates the list of columns that we can pick as the view
2. `fill_value`: will fill in all the NAN values.
3. `Margin_value` = `True/False`: Will provide the mean weight of the summary statistics of rows and overall columns

df.groupby("CPI")["Weekly_Sales"].agg[max]