In this notebook, we will cover topics related to Slicing and Indexing of data. We will cover **subsetting using Sliciing** and **Indexes and Subsetting Using Indexes**.

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)

2.2.3

In [2]:
df = pd.read_csv('data/churn.csv')
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [3]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

### Explicit Indexes

`df.set_index("Column_name")`; Will help you set a particular column as an index.

In [7]:
SetIndex = df.set_index('Surname')
print(SetIndex)

           RowNumber  CustomerId  CreditScore Geography  Gender  Age  Tenure  \
Surname
Hargrave           1    15634602          619    France  Female   42       2
Hill               2    15647311          608     Spain  Female   41       1
Onio               3    15619304          502    France  Female   42       8
Boni               4    15701354          699    France  Female   39       1
Mitchell           5    15737888          850     Spain  Female   43       2
...              ...         ...          ...       ...     ...  ...     ...
Obijiaku        9996    15606229          771    France    Male   39       5
Johnstone       9997    15569892          516    France    Male   35      10
Liu             9998    15584532          709    France  Female   36       7
Sabbatini       9999    15682355          772   Germany    Male   42       3
Walker         10000    15628319          792    France  Female   28       4

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
Surname
Hargrave        0.00              1          1               1
Hill        83807.86              1          0               1
Onio       159660.80              3          1               0
Boni            0.00              2          0               0
Mitchell   125510.82              1          1               1
...              ...            ...        ...             ...
Obijiaku        0.00              2          1               0
Johnstone   57369.61              1          1               1
Liu             0.00              1          0               1
Sabbatini   75075.31              2          1               0
Walker     130142.79              1          1               0

           EstimatedSalary  Exited
Surname
Hargrave         101348.88       1
Hill             112542.58       0
Onio             113931.57       1
Boni              93826.63       0
Mitchell          79084.10       0
...                    ...     ...
Obijiaku          96270.64       0
Johnstone        101699.77       0
Liu               42085.58       1
Sabbatini         92888.52       1
Walker            38190.78       0

[10000 rows x 13 columns]

`df.reset_index()`: This function will help reset the index .

In [10]:
SetIndex.reset_index()
print(SetIndex)

           RowNumber  CustomerId  CreditScore Geography  Gender  Age  Tenure  \
Surname
Hargrave           1    15634602          619    France  Female   42       2
Hill               2    15647311          608     Spain  Female   41       1
Onio               3    15619304          502    France  Female   42       8
Boni               4    15701354          699    France  Female   39       1
Mitchell           5    15737888          850     Spain  Female   43       2
...              ...         ...          ...       ...     ...  ...     ...
Obijiaku        9996    15606229          771    France    Male   39       5
Johnstone       9997    15569892          516    France    Male   35      10
Liu             9998    15584532          709    France  Female   36       7
Sabbatini       9999    15682355          772   Germany    Male   42       3
Walker         10000    15628319          792    France  Female   28       4

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
Surname
Hargrave        0.00              1          1               1
Hill        83807.86              1          0               1
Onio       159660.80              3          1               0
Boni            0.00              2          0               0
Mitchell   125510.82              1          1               1
...              ...            ...        ...             ...
Obijiaku        0.00              2          1               0
Johnstone   57369.61              1          1               1
Liu             0.00              1          0               1
Sabbatini   75075.31              2          1               0
Walker     130142.79              1          1               0

           EstimatedSalary  Exited
Surname
Hargrave         101348.88       1
Hill             112542.58       0
Onio             113931.57       1
Boni              93826.63       0
Mitchell          79084.10       0
...                    ...     ...
Obijiaku          96270.64       0
Johnstone        101699.77       0
Liu               42085.58       1
Sabbatini         92888.52       1
Walker            38190.78       0

[10000 rows x 13 columns]

In [13]:
df["Surname"].isin(["Walker"])
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

`df.sort_index()`: This function will help sort the index.

In [21]:
df.sort_index()
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

### Slicing and subsetting with .loc and iloc

`df.loc`: Will slice the dataframe. Here we need to specify index values of the list.

In [24]:
Surname = df.set_index(["Surname"]).sort_index()
Surname

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
Surname,,,,,,,,,,,,,
Abazu,3272,15708791,584,Spain,Male,32,9,85534.83,1,0,0,169137.24,0
Abazu,5110,15576156,710,Spain,Female,28,6,0.00,1,1,0,48426.98,0
Abbie,842,15737792,818,France,Female,31,1,186796.37,1,0,0,178252.63,0
Abbott,2989,15684801,689,France,Male,47,1,93871.95,3,1,0,156878.42,1
Abbott,4574,15693906,645,France,Female,24,3,34547.82,1,1,1,11638.17,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zuev,1031,15681174,730,France,Male,39,1,116537.60,1,0,0,145679.60,0
Zuyev,587,15722010,621,Spain,Male,53,9,170491.84,1,1,0,35588.07,1
Zuyev,6974,15583394,659,Germany,Male,39,8,106259.63,2,1,1,198103.32,0
Zuyeva,6386,15706810,606,Germany,Female,32,1,106301.85,2,0,1,59061.25,0
Zuyeva,7740,15689952,724,Spain,Male,41,5,0.00,1,0,1,115753.94,0

In [ ]:
Surname.loc["Abbott":"Zuev"]

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
Surname,,,,,,,,,,,,,
Abbott,2989,15684801,689,France,Male,47,1,93871.95,3,1,0,156878.42,1
Abbott,4574,15693906,645,France,Female,24,3,34547.82,1,1,1,11638.17,0
Abbott,6839,15680804,850,France,Male,29,6,0.00,2,1,1,10672.54,0
Abbott,2538,15723706,573,France,Female,33,0,90124.64,1,1,0,137476.71,0
Abdullah,8485,15601012,802,France,Female,60,3,92887.06,1,1,0,39473.63,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zubarev,5677,15568104,749,France,Female,26,6,0.00,2,0,1,34948.77,0
Zubarev,8815,15589725,740,France,Female,51,4,0.00,2,1,1,178929.84,0
Zubarev,6940,15807433,570,France,Female,43,9,0.00,2,0,1,11417.26,0
Zubareva,2947,15727696,592,France,Male,42,1,147249.29,2,1,1,63023.02,0
Zuev,1031,15681174,730,France,Male,39,1,116537.60,1,0,0,145679.60,0

As we can see from above example , just as we slice list  we must specify starting and ending value. `loc` function only performs the splitting on the index column, hence all inner columns do not work. To Slice inner index level we can follow the following method:

In [ ]:
Surname.loc[("Zubarev","5677"):("Zubarev","6940	")]

In [37]:
Surname.loc[:,"Geography":"Gender"]

        Geography  Gender
Surname
Abazu       Spain    Male
Abazu       Spain  Female
Abbie      France  Female
Abbott     France    Male
Abbott     France  Female
...           ...     ...
Zuev       France    Male
Zuyev       Spain    Male
Zuyev     Germany    Male
Zuyeva    Germany  Female
Zuyeva      Spain    Male

[10000 rows x 2 columns]

### Working with Pivot table

In [52]:
wallmartDf = pd.read_csv('data/Walmart.csv')
wallmartDf.columns
wallmartDf.head(10)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
5,1,12-03-2010,1439541.59,0,57.79,2.667,211.380643,8.106
6,1,19-03-2010,1472515.79,0,54.58,2.720,211.215635,8.106
7,1,26-03-2010,1404429.92,0,51.45,2.732,211.018042,8.106
8,1,02-04-2010,1594968.28,0,62.27,2.719,210.820450,7.808
9,1,09-04-2010,1545418.53,0,65.86,2.770,210.622857,7.808

In [59]:
wallmartDf.columns

Index(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',
       'Fuel_Price', 'CPI', 'Unemployment'],
      dtype='object')

In [68]:
Newdf = pd.pivot_table(wallmartDf,values=["Temperature","Weekly_Sales","Fuel_Price"],index="Date").sort_index()
Newdf

            Fuel_Price  Temperature  Weekly_Sales
Date
01-04-2011    3.602356    48.736444  9.657554e+05
01-06-2012    3.750822    72.943778  1.072926e+06
01-07-2011    3.675978    78.759111  1.057300e+06
01-10-2010    2.734333    69.868000  9.386639e+05
02-03-2012    3.696022    45.486444  1.041356e+06
...                ...          ...           ...
30-07-2010    2.766667    79.152222  9.917859e+05
30-09-2011    3.579644    72.788222  9.376851e+05
30-12-2011    3.271067    37.926222  1.023166e+06
31-08-2012    3.769067    77.793556  1.047992e+06
31-12-2010    3.048222    36.782667  8.985004e+05

[143 rows x 3 columns]

In [ ]:
Newdf.mean(axis="Fuel_Price")