In this Section we will cover feature Engineering. Feature engineering is the process of creation of new features from existing ones. This helps improve performance and give insight into relationships between features.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
voluenteer_df = pd.read_csv('data/Volunteering.csv')
voluenteer_df.head(10)

,opportunity_id,content_id,vol_requests,event_time,title,hits,summary,is_priority,category_id,category_desc,...,end_date_date,status,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,4996,37004,50,0,Volunteers Needed For Rise Up & Stay Put! Home...,737,Building on successful events last summer and ...,NaN,NaN,NaN,...,July 30 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5008,37036,2,0,Web designer,22,Build a website for an Afghan business,NaN,1.0,Strengthening Communities,...,February 01 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5016,37143,20,0,Urban Adventures - Ice Skating at Lasker Rink,62,Please join us and the students from Mott Hall...,NaN,1.0,Strengthening Communities,...,January 29 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5022,37237,500,0,Fight global hunger and support women farmers ...,14,The Oxfam Action Corps is a group of dedicated...,NaN,1.0,Strengthening Communities,...,March 31 2012,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5055,37425,15,0,Stop 'N' Swap,31,Stop 'N' Swap reduces NYC's waste by finding n...,NaN,4.0,Environment,...,February 05 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5056,37426,15,0,Queens Stop 'N' Swap,135,Stop 'N' Swap reduces NYC's waste by finding n...,NaN,4.0,Environment,...,February 12 2011,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5053,37406,2,0,Staff Development Trainer,156,The Jewish Museum seeks a volunteer staff deve...,NaN,1.0,Strengthening Communities,...,January 27 2012,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5085,37652,20,0,CLARO Brooklyn Volunteer Attorney,4407,"Provide legal advice, information and resource...",y,2.0,Helping Neighbors in Need,...,February 07 2012,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5091,37730,100,0,Join Cents Ability!,325,Join the Cents Ability volunteer corps to teac...,NaN,NaN,NaN,...,February 08 2012,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,5093,37741,1,0,Volunteer-Community Health Advocates,928,Community Health Advocates (CHA);formerly NYC ...,NaN,5.0,Health,...,February 09 2012,approved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
voluenteer_df.columns

Index(['opportunity_id', 'content_id', 'vol_requests', 'event_time', 'title',
       'hits', 'summary', 'is_priority', 'category_id', 'category_desc',
       'amsl', 'amsl_unit', 'org_title', 'org_content_id', 'addresses_count',
       'locality', 'region', 'postalcode', 'primary_loc', 'display_url',
       'recurrence_type', 'hours', 'created_date', 'last_modified_date',
       'start_date_date', 'end_date_date', 'status', 'Latitude', 'Longitude',
       'Community Board', 'Community Council ', 'Census Tract', 'BIN', 'BBL',
       'NTA'],
      dtype='object')

## Encoding Categorical Variables

In [10]:
# Data Cleaning
voluenteer_df.fillna(value='0', inplace=True)
voluenteer_df.head(10)

,opportunity_id,content_id,vol_requests,event_time,title,hits,summary,is_priority,category_id,category_desc,...,end_date_date,status,Latitude,Longitude,Community Board,Community Council,Census Tract,BIN,BBL,NTA
0,4996,37004,50,0,Volunteers Needed For Rise Up & Stay Put! Home...,737,Building on successful events last summer and ...,0,0,0,...,July 30 2011,approved,0,0,0,0,0,0,0,0
1,5008,37036,2,0,Web designer,22,Build a website for an Afghan business,0,1.0,Strengthening Communities,...,February 01 2011,approved,0,0,0,0,0,0,0,0
2,5016,37143,20,0,Urban Adventures - Ice Skating at Lasker Rink,62,Please join us and the students from Mott Hall...,0,1.0,Strengthening Communities,...,January 29 2011,approved,0,0,0,0,0,0,0,0
3,5022,37237,500,0,Fight global hunger and support women farmers ...,14,The Oxfam Action Corps is a group of dedicated...,0,1.0,Strengthening Communities,...,March 31 2012,approved,0,0,0,0,0,0,0,0
4,5055,37425,15,0,Stop 'N' Swap,31,Stop 'N' Swap reduces NYC's waste by finding n...,0,4.0,Environment,...,February 05 2011,approved,0,0,0,0,0,0,0,0
5,5056,37426,15,0,Queens Stop 'N' Swap,135,Stop 'N' Swap reduces NYC's waste by finding n...,0,4.0,Environment,...,February 12 2011,approved,0,0,0,0,0,0,0,0
6,5053,37406,2,0,Staff Development Trainer,156,The Jewish Museum seeks a volunteer staff deve...,0,1.0,Strengthening Communities,...,January 27 2012,approved,0,0,0,0,0,0,0,0
7,5085,37652,20,0,CLARO Brooklyn Volunteer Attorney,4407,"Provide legal advice, information and resource...",y,2.0,Helping Neighbors in Need,...,February 07 2012,approved,0,0,0,0,0,0,0,0
8,5091,37730,100,0,Join Cents Ability!,325,Join the Cents Ability volunteer corps to teac...,0,0,0,...,February 08 2012,approved,0,0,0,0,0,0,0,0
9,5093,37741,1,0,Volunteer-Community Health Advocates,928,Community Health Advocates (CHA);formerly NYC ...,0,5.0,Health,...,February 09 2012,approved,0,0,0,0,0,0,0,0

In [13]:
df = voluenteer_df
df['is_priority'].unique()

array(['0', 'y'], dtype=object)

In [14]:
df['is_priority_enc'] = df['is_priority'].apply(lambda val:1 if val=='y' else 0)
df[['is_priority_enc','is_priority']]

     is_priority_enc is_priority
0                  0           0
1                  0           0
2                  0           0
3                  0           0
4                  0           0
..               ...         ...
660                0           0
661                0           0
662                0           0
663                0           0
664                0           0

[665 rows x 2 columns]

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df2 = voluenteer_df

df2['is_priority_enc'] = le.fit_transform(df2['is_priority'])
df2[['is_priority_enc','is_priority']]

     is_priority_enc is_priority
0                  0           0
1                  0           0
2                  0           0
3                  0           0
4                  0           0
..               ...         ...
660                0           0
661                0           0
662                0           0
663                0           0
664                0           0

[665 rows x 2 columns]

## One Hot Encoding:
One hot encoding is another method that encodes categorical variables with multiple values.

In [16]:
print(df2['category_desc'])

0                              0
1      Strengthening Communities
2      Strengthening Communities
3      Strengthening Communities
4                    Environment
                 ...
660    Helping Neighbors in Need
661    Strengthening Communities
662    Helping Neighbors in Need
663    Strengthening Communities
664    Strengthening Communities
Name: category_desc, Length: 665, dtype: object

In [17]:
print(pd.get_dummies(df2['category_desc']))

         0  Education  Emergency Preparedness  Environment  Health  \
0     True      False                   False        False   False
1    False      False                   False        False   False
2    False      False                   False        False   False
3    False      False                   False        False   False
4    False      False                   False         True   False
..     ...        ...                     ...          ...     ...
660  False      False                   False        False   False
661  False      False                   False        False   False
662  False      False                   False        False   False
663  False      False                   False        False   False
664  False      False                   False        False   False

     Helping Neighbors in Need  Strengthening Communities
0                        False                      False
1                        False                       True
2                        False                       True
3                        False                       True
4                        False                      False
..                         ...                        ...
660                       True                      False
661                      False                       True
662                       True                      False
663                      False                       True
664                      False                       True

[665 rows x 7 columns]

## Engineering Numerical Features:

In [18]:
print(df2['end_date_date'])

0           July 30 2011
1       February 01 2011
2        January 29 2011
3          March 31 2012
4       February 05 2011
             ...
660     November 15 2012
661        April 13 2011
662    September 01 2011
663          May 31 2012
664      October 06 2012
Name: end_date_date, Length: 665, dtype: object

In [19]:
df2['Date_Converted'] = pd.to_datetime(df2['end_date_date'])
df2['Month'] = df2['Date_Converted'].dt.month

print(df2[['Date_Converted','Month','end_date_date']])

    Date_Converted  Month      end_date_date
0       2011-07-30      7       July 30 2011
1       2011-02-01      2   February 01 2011
2       2011-01-29      1    January 29 2011
3       2012-03-31      3      March 31 2012
4       2011-02-05      2   February 05 2011
..             ...    ...                ...
660     2012-11-15     11   November 15 2012
661     2011-04-13      4      April 13 2011
662     2011-09-01      9  September 01 2011
663     2012-05-31      5        May 31 2012
664     2012-10-06     10    October 06 2012

[665 rows x 3 columns]

## Engineering text features:

**Extractions**: Extracting data from text fields and then converting it into a features.

In [21]:
import re

my_string = "Temperature:75.6F"

temp = re.search("\d+\.\d+",my_string)

print(float(temp.group(0)))

75.6

<>:5: SyntaxWarning: invalid escape sequence '\d'
<>:5: SyntaxWarning: invalid escape sequence '\d'
/var/folders/zb/bl3vjblx59ggp4ygks32q_7r0000gn/T/ipykernel_6204/30353582.py:5: SyntaxWarning: invalid escape sequence '\d'
  temp = re.search("\d+\.\d+",my_string)

#### Vectorizing Text

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer


tf = TfidfVectorizer()
text_tfidf = tf.fit_transform(df2['category_desc'])